apiVersion: v1 
kind: Service
metadata:
  name: mongo-service
  #namespace: database
  namespace: suporte
spec:
  externalName: mongo-service.database.svc.cluster.local
  #externalName: mongo-service.suporte.svc.cluster.local
  type: ExternalName
